version: '3.8'

services:
  frontend:
    container_name: flowscribe_frontend_prod
    env_file: .env
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '7000:7000'
    restart: always
    depends_on:
      - middleware

  middleware:
    container_name: flowscribe_middleware_prod
    env_file: .env
    build:
      context: ./middleware
      dockerfile: Dockerfile
    ports:
      - '6000:6000'
    restart: always
    depends_on:
      - backend

  backend:
    container_name: flowscribe_backend_prod
    env_file: .env
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    restart: always
    depends_on:
      - db
    command: sh -c "npx tsx src/database/run_migrations.ts && npm start"

  db:
    container_name: flowscribe_postgres_prod
    env_file: .env
    image: postgres:15-alpine
    ports:
      - '54322:5432'
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    restart: always

  redis:
    container_name: flowscribe_redis_prod
    env_file: .env
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_prod_data:/data
    restart: always

  pgadmin:
    container_name: flowscribe_pgadmin_prod
    image: dpage/pgadmin4
    env_file: .env
    ports:
      - '5050:80'
    depends_on:
      - db
    volumes:
      - pgadmin_prod_data:/var/lib/pgadmin
    restart: always

volumes:
  postgres_prod_data:
  redis_prod_data:
  pgadmin_prod_data:
